Fix #111 paginate a list of entries
dmm-com/pagoda pull request #114
Opened 2021-04-14 15:49 UTC by syucream

https://github.com/dmm-com/airone/issues/111

It shows a pagination navigator like:
![image](https://user-images.githubusercontent.com/191684/114739978-5f986980-9d84-11eb-9b52-614dbf1f007e.png)

2021-05-19 06:46 UTC, hinashi requested changes
When I opened the link on the next page after narrowing down by keyword, the keyword disappeared.
![image](https://user-images.githubusercontent.com/5561786/118767892-4883f480-b8b9-11eb-8bec-0455ac11bf8d.png)
![image](https://user-images.githubusercontent.com/5561786/118767930-546fb680-b8b9-11eb-8923-9f738f3c5f4f.png)

2021-06-02 06:06 UTC, hinashi approved these changes
LGTM!
Thank you for fixing.

2021-06-09 01:48 UTC, userlocalhost reviewed
Thank you very much for implementing this feature smartly. But there seems to be unnecessary files. Would you please check it?

2021-06-09 01:48 UTC, userlocalhost commented on templates/frontend/main.js
> +(()=>{var e={676:(e,t,n)=>{"use strict";function r(e,t){(null==t||t>e.length)&&(t=e.length);for(var n=0,r=new Array(t);n<t;n++)r[n]=e[n];return r}n.d(t,{Z:()=>r})},3349:(e,t,n)=>{"use strict";functio
This seems like a file which is generated by React. Is this expected?

2021-06-09 01:48 UTC, userlocalhost commented on templates/frontend/main.js.LICENSE.txt
> + */
This file also seems like a file which is generated by React automatically. Is it necessary to manage it in this repository?

2021-06-14 06:08 UTC, userlocalhost approved these changes
LGTM 👍 

I'll do following work as another PR.
* Remove unnecessary files (e.g. templates/frontend/main.js)
* Add changelog

2021-06-14 06:08 UTC, merged