Replace ldap3 with python-ldap
dmm-com/pagoda pull request #134
Opened 2021-05-22 01:44 UTC by syucream

https://github.com/dmm-com/airone/issues/132

Replace [ldap3](https://pypi.org/project/ldap3/) with [python-ldap](https://pypi.org/project/python-ldap)

2021-05-22 01:44 UTC, syucream commented on README.md
> +user@hostname:~$ sudo apt-get install libldap2-dev
python-ldap is a Python binding to OpenLDAP library, so its required.

2021-05-22 14:44 UTC, takano32 approved these changes

2021-05-22 15:28 UTC, userlocalhost commented
I amazed how fast your work is! I'm so appreciated it.

2021-06-07 01:56 UTC, userlocalhost requested changes
Thank you very much for implementing this feature. But it won't work properly with the LDAP server of production environment.

This is execution result in the master branch (commit position is 615747ff40301148be0f2299c4a7691a897efc26) with changing `airone/settings.py` that sets LDAP configuration for production server. It passes authentication by `LDAPBackend.is_authenticated()` method.
<img width="540" alt="スクリーンショット 2021-06-07 11 01 16" src="https://user-images.githubusercontent.com/469934/120949601-d26c0280-c77f-11eb-8430-e2f8fd16657b.png">

After mering this PR to that master branch, I recreated virtualenv and run it with the same `airone/settings.py` as below.
<img width="587" alt="スクリーンショット 2021-06-07 10 40 31" src="https://user-images.githubusercontent.com/469934/120949097-a9973d80-c77e-11eb-9b0e-05611dc350f6.png">
<img width="1310" alt="スクリーンショット 2021-06-07 11 00 04" src="https://user-images.githubusercontent.com/469934/120949620-dd269780-c77f-11eb-9ffb-55174d6fcae5.png">

As a result, I couldn't pass authenticatoin with its LDAP server.
Could you please fix it?

2021-06-07 06:18 UTC, syucream commented
@userlocalhost First of all, did you install `libldap2-dev` and `libsasl2-dev`? It requires these C libraries.

Then, could you share your `airone/settings.py`? It might contain some breaking changes on settings I guess.
For information, my `airone/settings.py` which I test it with my testing LDAP server is here:
```
AUTHENTICATION_BACKENDS = (
    'airone.auth.ldap.LDAPBackend',
)

AUTH_CONFIG = {
    'LDAP': {
        'SERVER_ADDRESS': 'ldap://localhost:389',  # not to use TLS for now
        'USER_FILTER': 'cn={username},ou=people,dc=nodomain'
    }
}
```
I also confirmed calling LDAP directly works fine:
```
$ ldapwhoami -x -D "cn=user,ou=people,dc=nodomain" -W
Enter LDAP Password:
dn:cn=user,ou=people,dc=nodomain
```

2021-06-08 07:37 UTC, syucream commented
@userlocalhost To dig the root cause more, could you tell me details of your environment?

### 1. Use no-TLS connection

Could you try to connect LDAP server without TLS, like using `ldap://<hostname>:389/`?

### 2. Skip certificate validation

Could you specify this option in `/etc/ldap/ldap.conf` to ignore certificate validation?
```
TLS_REQCERT   never
```

...Unfortunately I haven't been able to reproduce your situation yet, so I need more hints. As a similar case, I got such a error when I use LDAP over TLS with a wrong CN in my (self-signed) certificate.
```
[ERROR] asctime:2021-06-08 16:30:41,593 module:ldap     message:{'result': -1, 'desc': "Can't contact LDAP server", 'errno': 2, 'ctrls': [], 'info': 'TLS: hostname does not match CN in peer certificate'}       process:31668   thread:139638732171008
```
In this case, I passed the error if I specify `TLS_REQCERT   never` or modify CN. It might be relating to the error you got.

2021-06-14 01:27 UTC, hinashi commented
When I tried it in my development environment, I got the same error.
```
[ERROR] asctime:2021-06-14 10:18:06,737 module:ldap     message:{'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (self signed certificate in certificate chain)'}      process:13503   thread:139783962650368
```

This is because the LDAP server is a self-signed certificate.
I solved it by adding the private key of the self-signed certificate to the certificate list specified in TLS_CACERT in /etc/ldap/ldap.conf.

2021-06-16 16:49 UTC, userlocalhost approved these changes
I understood this implementation works well in the proper environment. Thank you very much for digging into this problem and solving it, @hinashi. And thank you for your great work ,@syucream (sorry for making you trouble that is outside the scope of your responsibility).

2021-06-16 16:51 UTC, userlocalhost commented
I'll write this change to the changelog at https://github.com/dmm-com/airone/pull/152 after merging this PR.

2021-06-16 16:51 UTC, merged