Implement feature to be able to notify event to 3rd party system
dmm-com/pagoda pull request #135
Opened 2021-05-26 06:57 UTC by userlocalhost

This commit adds feature to be able to notify following Entry's events
to the 3rd party system through specifying WebHook URL.

* Creating Entry
* Updating Entry
* Deleting Entry

Those notifying feature have not been implemented yet, but this commit
enables user to register the endpoint which is called when those events
were happened.

And this commit update entity/models.py, so you have to update MySQL DB
schema as below.
```
alter table `entity_entity` add `is_enabled_webhook` tinyint(1) NOT NULL;
alter table `entity_entity` add `webhook_url` varchar(200) COLLATE utf8_unicode_ci NOT NULL;
alter table `entity_entity` add `webhook_headers` longtext COLLATE utf8_unicode_ci NOT NULL;
```

2021-06-01 03:52 UTC, userlocalhost commented
## Verification result
I confirmed that a notification request would be posted after creating Entry to the registered WebHook URL

### Registration information
This registers URL of StackStorm's custom webhook endpoint (c.f. https://docs.stackstorm.com/webhooks.html)
<img width="847" alt="スクリーンショット 2021-06-01 12 48 38" src="https://user-images.githubusercontent.com/469934/120263962-bd065c80-c2d7-11eb-8fbd-c42edb6340f1.png">

### API logs 
This is st2api log. I conformed a request to the registered path is received when an Entry is created
<img width="1659" alt="スクリーンショット 2021-06-01 12 43 25" src="https://user-images.githubusercontent.com/469934/120264132-19697c00-c2d8-11eb-9c49-a9189a36ad1e.png">

### Request payload
This is the context of sending request that contains information of created Entry.
<img width="965" alt="スクリーンショット 2021-06-01 12 43 45" src="https://user-images.githubusercontent.com/469934/120264193-39993b00-c2d8-11eb-9fbc-3280e8097c24.png">

2021-06-01 08:27 UTC, userlocalhost reviewed
@hinashi pointed out the current constraint of registering WebHook URL for each Entity. I'll fix it to be able to specify multiple WebHook URL for each Entity.

2021-06-01 08:27 UTC, userlocalhost commented on entity/models.py
> +    webhook_headers = models.TextField()
In this case, user can register only 1 webhook URL for 1 Entity. It might suffer users in the future.

2021-06-03 07:39 UTC, userlocalhost commented
The last commit changed this implementation to be able to specify multiple Webhook endpoints as below.
<img width="1193" alt="スクリーンショット 2021-06-03 16 37 27" src="https://user-images.githubusercontent.com/469934/120606508-3776de00-c48a-11eb-9433-9c41bdcafec6.png">

2021-06-03 09:43 UTC, userlocalhost commented
You have to create following tables to be able to use this feature on your current AirOne environment.
```
CREATE TABLE `webhook_webhook` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` longtext COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `is_enabled` tinyint(1) NOT NULL,
  `is_verified` tinyint(1) NOT NULL,
  `headers` longtext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `entity_entity_webhooks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_id` int(11) NOT NULL,
  `webhook_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `entity_entity_webhooks_entity_id_webhook_id_04c6c62d_uniq` (`entity_id`,`webhook_id`),
  KEY `entity_entity_webhooks_webhook_id_efb259b7_fk_webhook_webhook_id` (`webhook_id`),
  CONSTRAINT `entity_entity_webhoo_entity_id_ff7015ab_fk_entity_en` FOREIGN KEY (`entity_id`) REFERENCES `entity_entity` (`aclbase_ptr_id`),
  CONSTRAINT `entity_entity_webhooks_webhook_id_efb259b7_fk_webhook_webhook_id` FOREIGN KEY (`webhook_id`) REFERENCES `webhook_webhook` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

2021-06-04 03:34 UTC, hinashi requested changes
Notification failed if there is a Date type attribute.
![image](https://user-images.githubusercontent.com/5561786/120741854-ca6a5380-c530-11eb-8689-c7048f2a3d71.png)
![image](https://user-images.githubusercontent.com/5561786/120742003-1e753800-c531-11eb-972f-f78c6c30dd90.png)

2021-06-04 04:40 UTC, userlocalhost commented
@hinashi Thank you very much for checking in detail. I'll fix it soon.

2021-06-08 08:10 UTC, hinashi approved these changes
LGTM!
Thank you for fixing it.

2021-06-08 09:33 UTC, merged