[WIP] Added new feature of attribute-type 'array_group'
dmm-com/pagoda pull request #36
Opened 2020-09-03 00:17 UTC by userlocalhost

This adds a new attribute-type `array_group` that could handle multiple group values in an Attribute. This is similar with `array_string` and `array_object`.
By this change, user deal with system groups in their Entry without making any complicated and duplicated data structure and data.

## Note
This changes basic feature of this software. So it requires to make tests for following components carefully.

- AttriuteValue
  - [x] get_value
  - [x] format_for_history

- Attribute
  - [ ] is_upated
  - [x] add_value 
  - [ ] convert_value_to_register
  - [ ] remove_from_attrv
  - [ ] add_to_attrv

- Entry
  - [ ] (View) get_available_attrs
  - [ ] (for elasticsearch)

2020-09-10 05:47 UTC, userlocalhost commented
## Edit Entity
I confirmed `array_group` is selectable and submittable.
<img width="993" alt="スクリーンショット 2020-09-09 21 02 20" src="https://user-images.githubusercontent.com/469934/92685443-a9dee580-f372-11ea-9b06-2f27509b6eb6.png">

## Show/Edit Entry
I confirmed an Entry that has `array_group` value could be shown and edited.
<img width="679" alt="スクリーンショット 2020-09-10 14 36 34" src="https://user-images.githubusercontent.com/469934/92685650-2671c400-f373-11ea-99f3-b8ebfaab8a27.png">
<img width="907" alt="スクリーンショット 2020-09-10 14 37 01" src="https://user-images.githubusercontent.com/469934/92685656-283b8780-f373-11ea-8df8-93a0918add5a.png">

## Search Entry
<img width="863" alt="スクリーンショット 2020-09-10 14 39 22" src="https://user-images.githubusercontent.com/469934/92685895-8ff1d280-f373-11ea-9ada-116d19646b8f.png">
<img width="1193" alt="スクリーンショット 2020-09-10 14 40 01" src="https://user-images.githubusercontent.com/469934/92685903-92542c80-f373-11ea-9c83-54ab80b52f4e.png">

## Show update history of Entry 
<img width="1193" alt="スクリーンショット 2020-09-10 14 41 22" src="https://user-images.githubusercontent.com/469934/92685980-bca5ea00-f373-11ea-944a-f5c550c5e07c.png">

## Restore
<img width="822" alt="スクリーンショット 2020-09-10 14 42 41" src="https://user-images.githubusercontent.com/469934/92686094-f119a600-f373-11ea-8914-04c2a9b0b33d.png">

2020-09-11 00:00 UTC, takano32 commented on api_v1/tests/test_api.py
> +                'grps': ['group1', 'group2'],
`groups` でよいと思いました。
他は統一感があるのですが `grps` にした理由があればそのままでよさそうです。

2020-09-11 00:02 UTC, takano32 commented on entry/api_v1/views.py
> +            query_name = Q()
```
query_name = Q()
if keyword:
    query_name = Q(name__icontains=keyword)
```

の方が安全な書き方だと思うので `Q` の実行コストが低ければ上記のように書いてしまいましょう。

2020-09-11 04:19 UTC, takano32 requested changes
ひと通り読んで、直感的に分からなかった箇所、修正が望ましい箇所を指摘しました。

2020-09-11 04:19 UTC, takano32 commented on entry/models.py
> +                return group.name
このメソッド、戻り値の扱いが難しくないですか？

2020-09-11 04:19 UTC, takano32 commented on entry/models.py
> +        def _set_attrv(attr_type, val, attrv=None, params={}):
メソッドが大きすぎます。意味が分かる単位に分割できるとよいと思います。

2020-09-11 04:19 UTC, takano32 commented on entry/models.py
> +        def _set_attrv(attr_type, val, attrv=None, params={}):
分岐後の処理を `_set_attrv_type_string`, `_set_attrv_type_group`, `_set_attrv_type_object`, `_set_attrv_type_named_object` などに分割して読めるようにするといいと思っています。

2020-09-11 04:21 UTC, takano32 commented on entry/models.py
> +                return group.name
メソッド名から戻り値が簡単に判断できない、というのは使い方を間違えやすいのではないかという意図です。

2020-09-11 11:24 UTC, userlocalhost commented on entry/models.py
> +                return group.name
当該メソッド `get_value` は、属性型毎に異なる型の値を格納している AttributeValue から値を取り出すメソッドなので、返礼値の型が違っている感じです。

2020-09-11 11:25 UTC, userlocalhost commented on entry/models.py
> +        def _set_attrv(attr_type, val, attrv=None, params={}):
おっしゃる通りですので、リファクタリング Issue を作成致しました。
https://github.com/dmm-com/airone/issues/37

2020-09-11 11:48 UTC, merged