Implement password reset based on Django embedded features
dmm-com/pagoda pull request #84
Opened 2021-02-13 10:13 UTC by syucream

Currently Airone users cannot password reset themselves without admin helps. This patch allows them to reset their password with sending email, a typical way.

2021-02-21 15:25 UTC, syucream commented on airone/settings.py
> +EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
Any good settings for production usage?

2021-03-06 09:40 UTC, syucream commented on user/forms.py
> +class UsernameBasedPasswordResetForm(forms.Form):
It partially imports the original implementation in `django.contrib.auth.forms.PasswordResetForm` so it probably has licensing issue. How should we handle such a situation?

2021-03-15 01:27 UTC, userlocalhost reviewed
Thank you very much for making this feature. Would you please add the description of this feature to the CHANGELOG, and description how to use this feature (e.g. configuration to be able to send e-mails) to the README?

2021-03-15 06:50 UTC, userlocalhost requested changes
Could you please show warning message before sending an E-Mail for users who are `user.authenticate_type != AUTH_TYPE_LOCAL`?

This feature send an email for password reset for all kind of users. But it should not send its email and show following warning message for users who don't authenticate with Django's authentication system.

```
This user is configured to authenticate with LDAP. Please retry using that authenticate information.
```

Those users authenticate with LDAP (or other system, we plan to do with OAuth 2.0 in near future). Therefore, we shouldn't send a password reset email for those user whose authenticate type of its User instance is not AUTH_TYPE LOCAL.

2021-04-06 10:22 UTC, hinashi approved these changes
LGTM!
I have verified that password reset works in my local env.
Password validation has also been added thanks to django's auth library.
Since there is no validation when creating user and changing  password, we will consider adding it in the future.

2021-04-28 02:48 UTC, userlocalhost approved these changes
It's great work. Thanks!

2021-04-28 02:48 UTC, merged