Improve attributes search
dmm-com/pagoda pull request #97
Opened 2021-03-20 09:09 UTC by syucream

Cont'd from https://github.com/dmm-com/airone/pull/89, I would like to support some rich search options on attributes search.

2021-03-27 16:20 UTC, syucream commented on airone/lib/elasticsearch.py
> +    chars = escaped.replace('^', '^?').replace('$', '$?')
Its a breaking change! It makes ES query more ambiguous. If AirOne users use `^` and/or `$` on entry/attribute names and they hope to get exact search result with using these characters, they cannot get the same result.

2021-04-06 07:32 UTC, hinashi requested changes
The number of search results remained the number of hits in Elasticsearch.
If below, it is good if the search result is 1.
![image](https://user-images.githubusercontent.com/5561786/113674336-0c277b00-96f5-11eb-811a-412c9fd13f53.png)

2021-04-10 10:31 UTC, syucream commented
I modified it on https://github.com/dmm-com/airone/pull/97/commits/b11488368dad7d0727a5dd65c9a4a40d82b040d2 to count the number of actual entries. It seems to work fine.
![image](https://user-images.githubusercontent.com/191684/114266637-3a2cf800-9a32-11eb-9d2e-ad21656183ab.png)

But, unfortunately it breaks existing behavior on `make_search_results()`. Actually some test cases failed:
```
FAIL: test_search_entries (entry.tests.test_model.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/entry/tests/test_model.py", line 1547, in test_search_entries
    self.assertEqual(ret['ret_count'], 11)
AssertionError: 5 != 11

======================================================================
FAIL: test_search_result_count (entry.tests.test_model.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/entry/tests/test_model.py", line 2159, in test_search_result_count
    self.assertEqual(resp['ret_count'], 10)
AssertionError: 5 != 10

----------------------------------------------------------------------
Ran 459 tests in 189.234s

FAILED (failures=2, skipped=2)
```
Because `make_search_results()` returns the number of ES search results, NOT the actual number of entries on the page, 😢  in the test case, it expects 11 as a count even if limit = 5 and the number of entries is also 5.

Then how do we handle the number? I think possible options are:
- Change the existing logic to get a count thats the same value with the actual number of entries
  - `make_search_results()` is called by `/api/v1/entry/search`, so it breaks API compatibility.
- Put the problem on ice. We just revert  https://github.com/dmm-com/airone/pull/97/commits/b11488368dad7d0727a5dd65c9a4a40d82b040d2

2021-04-14 07:49 UTC, hinashi commented
This is a difficult problem ...
I thought about do _is_matched_entry all the search results of elasticsearch, but it's not smart.

I think it's better to revert b114883. sorry.

We wait for the opinions of others.

2021-04-17 10:09 UTC, syucream commented
No problem, you're welcome! Anyway I revert it for now.

2021-04-21 01:09 UTC, hinashi approved these changes

2021-04-29 06:38 UTC, userlocalhost reviewed
Thank you very much for your great job! This feature must help many customers, I believe.
But, I'm bother the result that shows wrong hit count.
<img width="608" alt="スクリーンショット 2021-04-29 15 44 05" src="https://user-images.githubusercontent.com/469934/116511665-c29c0b80-a901-11eb-887d-70f580f2eea5.png">

How about following solution to subtract hit count from the elasticsearch results when user specified special characters (`^` or `$`)?
https://github.com/syucream/airone/pull/5

(I need test to confirm the 'ret_count' that returns make_search_results will be expected when the parameter "hint_attrs" contains the special characters (`^` or `$`) and matches prepared entries).

If you satisfied with above PR, I'm glad for you to merge it.

2021-05-01 08:09 UTC, syucream commented
@userlocalhost I fixed it, could you take another look? 🙇

2021-05-06 04:11 UTC, userlocalhost reviewed
Thank you very much for your great work :+1:

I would really appreciate it if you could apply those special search options to the referral attribute values.
(e.g. At the following case, I want to get only entries which matches "^ほげ" at the `ref` attribute, but AirOne returns entries which don't match this filter, that is Entry "hoge" as below).
<img width="1186" alt="スクリーンショット 2021-05-06 13 04 54" src="https://user-images.githubusercontent.com/469934/117240734-7a826900-ae6c-11eb-8716-77139190285b.png">

2021-05-07 16:06 UTC, syucream commented
@userlocalhost it caused by attr type limitation that applied only `string` or `text` types, so I mitigated it at https://github.com/dmm-com/airone/pull/97/commits/fc83fdbb466d73749eef5688d2c2063699abfc6b.

What do you think about remaining types, `'date', 'array', 'array_group', 'array_named_object', 'array_object', 'array_string'`? My current implementation just ignores these types.

For more details, about `date` type, I found a wrong behavior (might be a bug?) that seems not to accept attr hints on the current master branch https://github.com/dmm-com/airone/commit/ce3c199f23c595a7c029ee52b57297b3666343e3, like this:
![image](https://user-images.githubusercontent.com/191684/117477182-a7cc3580-af98-11eb-84c6-0dd08ab29db9.png)
then:
![image](https://user-images.githubusercontent.com/191684/117477263-c03c5000-af98-11eb-9658-7ebb53b896b6.png)
Whats the correct behavior?

About other `array` types, I don't know which behavior is correct. The current attr hints performs OR matching on multiple elements, like this:
![image](https://user-images.githubusercontent.com/191684/117477535-127d7100-af99-11eb-869a-c780891c148d.png)
then:
![image](https://user-images.githubusercontent.com/191684/117477557-18735200-af99-11eb-9ed6-c910017b5eee.png)
and also:
![image](https://user-images.githubusercontent.com/191684/117477584-21642380-af99-11eb-8a0a-f3df5928b229.png)

Should we apply the regex based attr hints like that way, or just ignoring?

2021-05-12 08:56 UTC, userlocalhost reviewed
> What do you think about remaining types, 'date', 'array', 'array_group', 'array_named_object', 'array_object', 'array_string'? My current implementation just ignores these types.

OK, we should make a limitation to be able to apply this feature only for `string` and `text` typed attribute values for now, I think.
But this limitation should be fixed in near future. So, could you please make an issue for this limitation, @syucream?

After making that issue, I'll merge this PR.

Thank you.

2021-05-15 08:26 UTC, syucream commented
@userlocalhost Sure! So I revert the latest modification by https://github.com/dmm-com/airone/pull/97/commits/4d32d0b7ec54de41e0e2b1c7aad1316e1c64ba05, and I created a new issue https://github.com/dmm-com/airone/issues/129 to aim a problem on `date` attribute.

Anyway, could you take another look? 🙇

2021-06-07 02:27 UTC, userlocalhost reviewed
LGTM 👍 Thank you very much for your work.

@syucream 
Before merging it. Would you please add description of this feature including restriction (which is described with #129) in the README for next release.

I'll merge it after adding those description will be added in the README.

2021-06-08 01:53 UTC, merged